import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../models/review.dart';
import '../models/user_class.dart';
import '../repositories/review_repository.dart';
import 'package:textpass/utils/app_toast.dart';

class ReviewComposeScreen extends ConsumerStatefulWidget {
  final UserClass userClass; // Data from ClassDetailScreen

  const ReviewComposeScreen({super.key, required this.userClass});

  @override
  ConsumerState<ReviewComposeScreen> createState() =>
      _ReviewComposeScreenState();
}

class _ReviewComposeScreenState extends ConsumerState<ReviewComposeScreen> {
  final _formKey = GlobalKey<FormState>();

  double _rating = 3.0; // Default 3
  String _difficulty = 'normal';
  bool _hasTest = false;
  bool _hasReport = false;
  String _attendance = 'sometimes';
  String _textbook = 'not_needed';
  final _commentController = TextEditingController();
  bool _isSubmitting = false;

  @override
  void dispose() {
    _commentController.dispose();
    super.dispose();
  }

  Future<void> _submitReview() async {
    if (!_formKey.currentState!.validate()) return;
    final user = FirebaseAuth.instance.currentUser;
    if (user == null) {
      AppToast.show(context, 'ログインが必要です');
      return;
    }

    // Check if duplicate
    final hasReviewed =
        await ref.read(reviewRepositoryProvider).hasUserReviewed(
              user.uid,
              widget.userClass.title,
              widget.userClass.teacher,
              classKey: widget.userClass.classKey,
            );

    if (hasReviewed) {
      if (mounted) {
        AppToast.show(context, '既にこの授業のレビューを投稿済みです');
      }
      return;
    }

    setState(() {
      _isSubmitting = true;
    });

    try {
      final review = Review(
        id: '', // Auto-generated by Firestore
        userId: user.uid,
        title: widget.userClass.title,
        teacher: widget.userClass.teacher,
        classKey: widget.userClass.classKey,
        year: widget.userClass.year, // Using the year from UserClass!
        rating: _rating,
        difficulty: _difficulty,
        hasTest: _hasTest,
        hasReport: _hasReport,
        attendance: _attendance,
        textbook: _textbook,
        comment: _commentController.text.trim(),
        createdAt: DateTime.now(),
      );

      await ref.read(reviewRepositoryProvider).addReview(review);

      if (mounted) {
        AppToast.show(context, 'レビューを投稿しました！');
        Navigator.pop(context, true); // Return success signal
      }
    } catch (e) {
      if (mounted) {
        AppToast.show(context, 'エラーが発生しました: $e');
      }
    } finally {
      if (mounted) {
        setState(() {
          _isSubmitting = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('レビューを書く'),
        actions: [
          TextButton(
            onPressed: _isSubmitting ? null : _submitReview,
            child:
                const Text('投稿', style: TextStyle(fontWeight: FontWeight.bold)),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Class Info Header
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.grey.shade100,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(widget.userClass.title,
                        style: const TextStyle(
                            fontWeight: FontWeight.bold, fontSize: 16)),
                    const SizedBox(height: 4),
                    Text(
                        '${widget.userClass.teacher} / ${widget.userClass.year}年度',
                        style: TextStyle(color: Colors.grey.shade700)),
                  ],
                ),
              ),
              const SizedBox(height: 24),

              // 1. Rating
              const Text('総合評価', style: TextStyle(fontWeight: FontWeight.bold)),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: List.generate(5, (index) {
                  return IconButton(
                    iconSize: 40,
                    icon: Icon(
                      index < _rating ? Icons.star : Icons.star_border,
                      color: Colors.amber,
                    ),
                    onPressed: () {
                      setState(() {
                        _rating = index + 1.0;
                      });
                    },
                  );
                }),
              ),
              const SizedBox(height: 24),

              // 2. Difficulty
              const Text('単位の難易度',
                  style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                children: [
                  _buildChoiceChip('easy', '楽単', _difficulty == 'easy',
                      (val) => setState(() => _difficulty = 'easy')),
                  _buildChoiceChip('normal', '普通', _difficulty == 'normal',
                      (val) => setState(() => _difficulty = 'normal')),
                  _buildChoiceChip('hard', '鬼単', _difficulty == 'hard',
                      (val) => setState(() => _difficulty = 'hard')),
                ],
              ),
              const SizedBox(height: 24),

              // 3. Evaluation Method
              const Text('評価方法', style: TextStyle(fontWeight: FontWeight.bold)),
              Row(
                children: [
                  FilterChip(
                    label: const Text('テストあり'),
                    selected: _hasTest,
                    onSelected: (val) => setState(() => _hasTest = val),
                  ),
                  const SizedBox(width: 8),
                  FilterChip(
                    label: const Text('レポートあり'),
                    selected: _hasReport,
                    onSelected: (val) => setState(() => _hasReport = val),
                  ),
                ],
              ),
              const SizedBox(height: 24),

              // 4. Attendance
              const Text('出席確認', style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                children: [
                  _buildChoiceChip('always', '毎回あり', _attendance == 'always',
                      (val) => setState(() => _attendance = 'always')),
                  _buildChoiceChip(
                      'sometimes',
                      'たまに',
                      _attendance == 'sometimes',
                      (val) => setState(() => _attendance = 'sometimes')),
                  _buildChoiceChip('none', 'なし', _attendance == 'none',
                      (val) => setState(() => _attendance = 'none')),
                ],
              ),
              const SizedBox(height: 24),

              // 5. Textbook
              const Text('教科書', style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                children: [
                  _buildChoiceChip('required', '必須', _textbook == 'required',
                      (val) => setState(() => _textbook = 'required')),
                  _buildChoiceChip(
                      'not_needed',
                      '不要/配布',
                      _textbook == 'not_needed',
                      (val) => setState(() => _textbook = 'not_needed')),
                ],
              ),
              const SizedBox(height: 24),

              // 6. Comment
              const Text('コメント', style: TextStyle(fontWeight: FontWeight.bold)),
              const SizedBox(height: 4),
              const Text(
                '※講師や特定の人物への誹謗中傷となるコメントは控えてください。',
                style: TextStyle(color: Colors.grey, fontSize: 12),
              ),
              const SizedBox(height: 8),
              TextFormField(
                controller: _commentController,
                maxLines: 5,
                decoration: const InputDecoration(
                  hintText: '授業の感想やアドバイスを記入してください',
                  border: OutlineInputBorder(),
                ),
              ),
              const SizedBox(height: 40),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildChoiceChip(
      String value, String label, bool selected, Function(bool) onSelected) {
    return ChoiceChip(
      label: Text(label),
      selected: selected,
      onSelected: onSelected,
    );
  }
}
